name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-nextjs.yml@master
    with:
      domain: schort.ir
      base-href: /
      process-name: schort.ir
      port: 3002
    secrets: inherit
